name: Tests

on:
  pull_request:
    branches: [main]

env:
  JAVA_VERSION: 17
  JAVA_DIST: "zulu"

jobs:
  android-unit-tests:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run unit tests
        run: ./gradlew assembleDebug testDebug iosSimulatorArm64Test

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: android-unit-test-reports
          path: |
            **/build/reports/tests
            **/build/reports/androidTests/connected
            uitest-screenshot-failure

  android-integration-tests:
    runs-on: macos-12
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [
          29, # Android 10
          30, # Android 11
#          32, # Android 12
#          33, # Android 13
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86
          disable-animations: false
          emulator-build: 7425822 # workaround to emulator bug: https://github.com/ReactiveCircus/android-emulator-runner/issues/160
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            ./gradlew connectedDebugAndroidTest || (adb exec-out "run-as com.hulkdx.findprofessional cp -r files/uitest-screenshot-failure /sdcard/uitest-screenshot-failure" && adb pull sdcard/uitest-screenshot-failure && exit 1)

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: android-integration-test-reports
          path: |
            **/build/reports/tests
            **/build/reports/androidTests/connected
            uitest-screenshot-failure

  ios-tests:
    name: iOS tests
    runs-on: macos-12
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.2.app

      - uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Get cached Swift Packages managed by Xcode
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Xcode/DerivedData/**/SourcePackages/
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build and Test
        run: xcodebuild
          -workspace ios/FindProffessional.xcodeproj/project.xcworkspace
          -scheme FindProfessional
          -configuration Debug
          -sdk iphonesimulator
          -destination 'platform=iOS Simulator,name=iPhone 14'
          build test
          ONLY_ACTIVE_ARCH=YES
          CODE_SIGNING_REQUIRED=NO
          CODE_SIGN_IDENTITY=""
