name: Tests

on:
  pull_request:
    branches: [ main ]

env:
  JAVA_VERSION: 17
  JAVA_DIST: "zulu"
  IOS_XCODE_VERSION: "15.0.1"

jobs:
  unit-tests-android-and-ios:
    name: Unit test on Android and IOS
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run unit tests
        run: ./gradlew assembleDebug testDebug iosSimulatorArm64Test

      # TODO: 
      # - name: Run screenshot tests
      #   run: ./gradlew :android:paparazzi-tests:verifyPaparazziDebug

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: android-unit-test-reports
          path: |
            **/build/reports/tests
            **/build/reports/androidTests/connected
            uitest-screenshot-failure

  android-integration-tests:
    name: Android Integration tests
    runs-on: macos-12
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - api-level: 34 # Android 15
            arch: x86_64
            target: default

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Android instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          target: ${{ matrix.target }}
          disable-animations: false
          emulator-build: 11834374
          emulator-options: -no-snapshot -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -camera-front none
          script: >
            ./gradlew connectedAndroidTest ||
            (adb pull sdcard/Download/uitest-screenshot-failure &&
            exit 1)

      - name: Upload Android test reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: android-integration-test-reports-${{ matrix.api-level }}
          path: |
            **/build/reports/tests
            **/build/reports/androidTests/connected
            uitest-screenshot-failure


  ios-integration-tests:
    name: IOS Integration tests
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_${{ env.IOS_XCODE_VERSION }}.app

      - uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run IOS instrumentation tests
        run: ./gradlew :app:iosSimulatorArm64Test

      - name: Upload IOS test reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: ios-integration-test-reports-${{ matrix.api-level }}
          path: |
            **/build/reports/tests
